# Generated by Django 4.1.12 on 2023-11-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framely', '0004_remove_post_foto_post_foto_video_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto_video',
            field=models.FileField(blank=True, null=True, upload_to='posts', verbose_name='foto_video'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuario', verbose_name='foto_perfil'),
        ),
    ]
