# Generated by Django 4.1.12 on 2023-11-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framely', '0005_alter_post_foto_video_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
