# Generated by Django 4.1.12 on 2023-11-04 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('framely', '0007_alter_usuario_email_alter_usuario_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha',
        ),
    ]
