# Generated by Django 4.1.12 on 2023-10-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framely', '0002_remove_usuario_apellido_remove_usuario_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='usuarios'),
        ),
    ]
