# Generated by Django 4.1.12 on 2023-11-04 19:12

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('framely', '0008_remove_post_fecha_alter_post_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='usuario',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
